apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloopbackoff-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashloopbackoff-demo
  template:
    metadata:
      labels:
        app: crashloopbackoff-demo
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        command: ["sh", "-c", "sleep 3600"]
        ports:
        - containerPort: 80