apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloopbackoff-demo
  labels:
    app: crashloopbackoff
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crashloopbackoff
  template:
    metadata:
      labels:
        app: crashloopbackoff
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80