apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloopbackoff-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashloopbackoff-demo
  template:
    metadata:
      labels:
        app: crashloopbackoff-demo
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        # Removed the problematic 'sleep 1' command
        # Now nginx will run normally as a web server